# ETAPA 1: Builder
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY packages/admin-portal/package*.json ./packages/admin-portal/

RUN npm install

COPY packages/admin-portal ./packages/admin-portal

WORKDIR /app/packages/admin-portal
RUN npm run build

# ETAPA 2: Runner
FROM node:20-alpine
WORKDIR /app

# Copiamos node_modules de la raíz y la carpeta .next del paquete
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/admin-portal/.next ./.next
COPY --from=builder /app/packages/admin-portal/public ./public
COPY --from=builder /app/packages/admin-portal/package*.json ./

EXPOSE 5002

CMD ["npm", "start"]
