# ETAPA 1: Builder
FROM node:20-alpine AS builder
# Instalamos dependencias necesarias para compilar en Alpine
RUN apk add --no-cache openssl libc6-compat

WORKDIR /app

COPY package*.json ./
COPY packages/core-api/package*.json ./packages/core-api/

RUN npm install

COPY packages/core-api ./packages/core-api

WORKDIR /app/packages/core-api
RUN npx prisma generate
RUN npm run build

# ETAPA 2: Runner
FROM node:20-alpine
# TAMBIÉN instalamos las librerías en la etapa final
RUN apk add --no-cache openssl

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/core-api/dist ./dist
COPY --from=builder /app/packages/core-api/package*.json ./
COPY --from=builder /app/packages/core-api/prisma ./prisma

EXPOSE 5001

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/index.js"]
