# ETAPA 1: Builder
FROM node:20-slim AS builder

# Instalar dependencias necesarias para Prisma en Debian
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package*.json ./
COPY packages/core-api/package*.json ./packages/core-api/

RUN npm install

COPY packages/core-api ./packages/core-api

WORKDIR /app/packages/core-api
RUN npx prisma generate
RUN npm run build

# ETAPA 2: Runner
FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/core-api/dist ./dist

# COPIAMOS LA CARPETA CONFIG (Aquí va el swagger.yaml)
COPY --from=builder /app/packages/core-api/src/config ./src/config

COPY --from=builder /app/packages/core-api/package*.json ./
COPY --from=builder /app/packages/core-api/prisma ./prisma

EXPOSE 5001

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/src/server.js"]
